version: '3'
services:
  smkgts:
    container_name: smkgts_web
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - smkgts_net
    volumes:
      - ./container/nginx/smkgts.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    environment:
      KEY: $DIRECTUS_KEY
      SECRET: $DIRECTUS_SECRET
      ADMIN_EMAIL: $DIRECTUS_EMAIL
      ADMIN_PASSWORD: $DIRECTUS_PASS
      CORS_ENABLED: 'true'
      CORS_ORIGIN: $DIRECTUS_CORS_ORIGIN

networks:
  smkgts_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1300
