version: '3'
services:
  directus:
    container_name: directus
    image: directus/directus  
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: $DIRECTUS_KEY
      SECRET: $DIRECTUS_SECRET
      ADMIN_EMAIL: $DIRECTUS_EMAIL
      ADMIN_PASSWORD: $DIRECTUS_PASS
      CORS_ENABLED: 'true'
      CORS_ORIGIN: $DIRECTUS_CORS_ORIGIN
