version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    user: '1000'
    network_mode: 'host'
    restart: 'unless-stopped'
    #stdin_open: true
    #tty: true
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - ./jellyfin:/etc/jellyfin
      - ./jellyfin/cache:/var/cache/jellyfin
      - ./jellyfin/data:/var/lib/jellyfin
      - ./jellyfin/log:/var/log/jellyfin
      - /mnt/data:/mnt/data # volumes list
