services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: $PIHOLE_DOMAIN
    environment:
      TZ: $PIHOLE_TZ
      WEBPASSWORD: $PIHOLE_PASSWORD
      WEB_PORT: 8080
      VIRTUAL_HOST: $PIHOLE_DOMAIN
      PROXY_LOCATION: $PIHOLE_DOMAIN
      FTLCONF_LOCAL_IPV4: $PIHOLE_FTL_IP
      WEB_BIND_ADDR: "0.0.0.0"
      PIHOLE_DNS: '127.0.0.1#53;208.67.220.220;208.67.222.222'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 200.42.4.198
      - 200.49.130.52
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
